source :rubygems

gem 'sprockets'
gem 'sass'
gem 'sprockets-sass'
gem 'sprockets-helpers'
gem 'compass'
gem 'bootstrap-sass'

gem 'multi_json', github: 'intridea/multi_json'
gem 'grape', github: 'goodwink/grape'

gem 'redis'
gem 'redis-objects', require: 'redis/objects'
gem 'coffee-script'
gem 'rake'
gem 'execjs'
gem 'therubyracer'
gem 'mail'
gem 'racksh'
gem 'unicorn'
gem 'debugger'
gem 'jasmine'
gem 'stripe', github: 'stripe/stripe-ruby'
gem 'dwolla'
